services:
  auth-service:
    build: ./auth-service
    ports:
      - "8001:8000"
    networks:
      - voyageconnect-network
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - SECRET_KEY=velikitajnikljuckojitrebapromjenit
    depends_on:
      - mongo
    restart: unless-stopped

  destination-service:
    build: ./destination-service
    ports:
      - "8002:8000"
    networks:
      - voyageconnect-network
    environment:
      - SECRET_KEY=velikitajnikljuckojitrebapromjenit
    restart: unless-stopped

  post-service:
    build: ./post-service
    ports:
      - "8003:8000"
    networks:
      - voyageconnect-network
    environment:
      - SECRET_KEY=velikitajnikljuckojitrebapromjenit
    restart: unless-stopped

  comment-service:
    build: ./comment-service
    ports:
      - "8004:8000"
    networks:
      - voyageconnect-network
    environment:
      - SECRET_KEY=velikitajnikljuckojitrebapromjenit
    depends_on:
    - mongo
    - auth-service
    restart: unless-stopped

  forum-service:
    build: ./forum-service
    ports:
      - "8005:8000"
    networks:
      - voyageconnect-network
    environment:
      - SECRET_KEY=velikitajnikljuckojitrebapromjenit
    restart: unless-stopped

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - auth-service
      - destination-service
      - post-service
      - comment-service
      - forum-service
    networks:
      - voyageconnect-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - voyageconnect-network

networks:
  voyageconnect-network:
    driver: bridge

volumes:
  mongo_data:
